package:
  name: pyomo
  version: "4.2.10784"

source:
  fn: Pyomo-4.2.10784.tar.gz
  url: https://pypi.python.org/packages/source/P/Pyomo/Pyomo-4.2.10784.tar.gz
  md5: b5d0ffcb19a8b55904b8e42a28c3bf09
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyomo = pyomo:main
    #
    # Would create an entry point called pyomo that calls pyomo.main()

    - runbenders=pyomo.pysp.benders:Benders_main
    - runph=pyomo.pysp.phinit:PH_main
    - runef=pyomo.pysp.ef_writer_script:main
    - pysp2smps=pyomo.pysp.smps.pysp2smps:main
    - phsolverserver=pyomo.pysp.phsolverserver:main
    - scenariotreeserver=pyomo.pysp.scenariotree.scenariotreeserver:main
    - computeconf=pyomo.pysp.computeconf:main
    #- pyomoossolverservice=pyomo.os.OSSolverService:execute
    #- results_schema=pyomo.scripting.commands:results_schema
    - pyro_mip_server=pyomo.scripting.pyro_mip_server:main
    - test.pyomo=pyomo.scripting.runtests:runPyomoTests
    - pyomo=pyomo.scripting.pyomo_main:main
    - pyomo_ns=pyomo.scripting.commands:pyomo_ns
    - pyomo_nsc=pyomo.scripting.commands:pyomo_nsc
    - kill_pyro_mip_servers=pyomo.scripting.commands:kill_pyro_mip_servers
    - launch_pyro_mip_servers=pyomo.scripting.commands:launch_pyro_mip_servers
    - readsol=pyomo.scripting.commands:readsol
    - ossolverservice=pyomo.scripting.commands:OSSolverService
    - pyomo_python=pyomo.scripting.commands:pyomo_python
    #- pyomo_old=pyomo.scripting.pyomo_command:main

requirements:
  build:
    - python
    - setuptools
    - pyutilib >=5.2.3601
    - ply
    - nose
    - six >=1.6.1

  run:
    - python
    - setuptools
    - pyutilib >=5.2.3601
    - pyro4 >=4.41
    - ply
    - nose
    - six >=1.6.1

test:
  # Python imports
  imports:
    - pyomo
    - pyomo.bilevel
    - pyomo.bilevel.plugins
    - pyomo.bilevel.tests
    - pyomo.checker
    - pyomo.checker.plugins
    - pyomo.checker.plugins.checkers
    - pyomo.checker.plugins.checkers.model
    - pyomo.checker.plugins.checkers.py3k
    - pyomo.checker.plugins.checkers.sample
    - pyomo.checker.tests
    - pyomo.core
    - pyomo.core.base
    - pyomo.core.beta
    - pyomo.core.data
    - pyomo.core.plugins
    - pyomo.core.plugins.data
    - pyomo.core.plugins.transform
    - pyomo.core.preprocess
    - pyomo.core.tests
    - pyomo.core.tests.data
    - pyomo.core.tests.diet
    - pyomo.core.tests.examples
    - pyomo.core.tests.transform
    - pyomo.core.tests.unit
    - pyomo.dae
    - pyomo.dae.plugins
    - pyomo.dae.tests
    - pyomo.data
    - pyomo.environ
    - pyomo.environ.tests
    - pyomo.gdp
    - pyomo.gdp.plugins
    - pyomo.gdp.tests
    - pyomo.mpec
    - pyomo.mpec.plugins
    - pyomo.mpec.tests
    - pyomo.neos
    - pyomo.neos.plugins
    - pyomo.openopt
    - pyomo.openopt.plugins
    - pyomo.openopt.tests
    - pyomo.opt
    - pyomo.opt.base
    - pyomo.opt.blackbox
    - pyomo.opt.parallel
    - pyomo.opt.plugins
    - pyomo.opt.problem
    - pyomo.opt.results
    - pyomo.opt.solver
    - pyomo.opt.testing
    - pyomo.opt.tests
    - pyomo.opt.tests.base
    - pyomo.opt.tests.blackbox
    - pyomo.pysp
    - pyomo.pysp.plugins
    - pyomo.pysp.scenariotree
    - pyomo.pysp.smps
    - pyomo.pysp.tests
    - pyomo.pysp.tests.examples
    - pyomo.pysp.tests.scenariotreemanager
    - pyomo.pysp.tests.smps
    - pyomo.pysp.tests.unit
    - pyomo.pysp.util
    - pyomo.repn
    - pyomo.repn.beta
    - pyomo.repn.plugins
    - pyomo.repn.plugins.ampl
    - pyomo.repn.tests
    - pyomo.repn.tests.ampl
    - pyomo.scripting
    - pyomo.scripting.plugins
    - pyomo.solvers
    - pyomo.solvers.plugins
    - pyomo.solvers.plugins.converter
    - pyomo.solvers.plugins.smanager
    - pyomo.solvers.plugins.solvers
    - pyomo.solvers.plugins.testdriver
    - pyomo.solvers.tests
    - pyomo.solvers.tests.io
    - pyomo.solvers.tests.io.fd
    - pyomo.solvers.tests.mip
    - pyomo.solvers.tests.pickling
    - pyomo.util
    - pyomo.util.tests
    - pyomo.version
    - pyomo.version.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - runbenders --help
    - runph --help
    - runef --help
    - pysp2smps --help
    - phsolverserver --help
    - scenariotreeserver --help
    - computeconf --help
    #- pyomoossolverservice --help  # See https://software.sandia.gov/trac/pyomo/changeset/10572
    #- results_schema --help  # Bug
    - pyro_mip_server --help
    - test.pyomo --help
    - pyomo --help
    - pyomo_ns --help
    - pyomo_nsc --help
    #- kill_pyro_mip_servers --help
    #- launch_pyro_mip_servers --help
    #- readsol --help
    #- ossolverservice
    - pyomo_python --help
    #- pyomo_old --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyomo.org
  license: BSD License
  summary: 'Pyomo: Python Optimization Modeling Objects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
